spring:
  rabbitmq:
    port: 5672
    host: localhost
    password: guest
    username: guest
  datasource:
      driverClassName: com.mysql.jdbc.Driver
      username: root
      password: root
      url: jdbc:mysql://127.0.0.1/q?serverTimezone=Hongkong&useUnicode=true&characterEncoding=utf-8

  redis:
    port: 6379
    host: 127.0.0.1
  data:
    mongodb:
      uri: mongodb://localhost/1809a
    elasticsearch:
      cluster-nodes: localhost:9300
      repositories:
        enabled: true
      cluster-name: elasticsearch

server:
  port: 8084
